'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ArrowDown, ArrowUpRight, Check, ChevronRight, Menu, MessageCircle, Moon, Send, Sun, X, Mail, ShieldCheck } from 'lucide-react';
import { company } from '@/data/company';
import { services } from '@/data/services';

const nav = ['About', 'Services', 'Process', 'Capabilities', 'Gallery', 'Why MV', 'Contact'];
const workflow = ['Contract drawings', '3D modeling', 'Detailing', 'Shop drawings', 'Erection drawings', 'CNC / NC data', 'Fabrication'];

function SteelModel() { return <div className="model" aria-label="Animated structural steel frame illustration"><i /><i /><i /><i /><i /><i /><b>LIVE MODEL VIEW</b><span className="coord c1">X 041 / Y 107</span><span className="coord c2">CONNECTION A-04</span></div>; }
export default function Home() {
  const [light, setLight] = useState(false); const [menu, setMenu] = useState(false); const [chat, setChat] = useState(false); const [active, setActive] = useState(0); const [intro, setIntro] = useState(true); const [clocks, setClocks] = useState({ us: '—', india: '—' }); const [chatReply, setChatReply] = useState('Welcome to MV Designers. How can we help with your structural steel detailing requirements?'); const [chatQuestion, setChatQuestion] = useState(''); const [chatInput, setChatInput] = useState(''); const [chatSending, setChatSending] = useState(false);
  useEffect(() => { const saved = localStorage.getItem('mv-theme'); const isLight = saved ? saved === 'light' : matchMedia('(prefers-color-scheme: light)').matches; setLight(isLight); document.documentElement.dataset.theme = isLight ? 'light' : 'dark'; const t = setTimeout(()=>setIntro(false), 2300); const update = () => setClocks({ us: new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit'}).format(new Date()), india: new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',hour:'numeric',minute:'2-digit'}).format(new Date()) }); update(); const clock = setInterval(update, 60000); return ()=>{clearTimeout(t);clearInterval(clock)}; }, []);
  const theme = () => { const next = !light; setLight(next); localStorage.setItem('mv-theme', next ? 'light':'dark'); document.documentElement.dataset.theme = next ? 'light':'dark'; };
  const answer = async (topic: string) => { if (!topic.trim() || chatSending) return; setChatQuestion(topic); setChatSending(true); setChatReply('Thinking through that…'); try { const response = await fetch('/api/chatbot', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ topic }) }); const data = await response.json(); setChatReply(data.message || 'Please email the MV Designers team for project-specific information.'); } catch { setChatReply('I could not connect just now. Please email the MV Designers team for project-specific information.'); } finally { setChatSending(false); } };
  const submitChat = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const message = chatInput.trim(); if (!message) return; setChatInput(''); answer(message); };
  return <main onContextMenu={e=>e.preventDefault()}>
    {intro && <div className="intro"><button onClick={()=>setIntro(false)}>Skip intro</button><div className="intro-mark">MV<span>◇</span></div><p>STRUCTURAL DETAILING SYSTEM INITIALIZING</p><div className="load"><i /></div></div>}
    <div className="progress" />
    <header><a className="brand" href="#home"><small>STRUCTURAL</small>MV DESIGNERS</a><nav className={menu?'open':''}>{nav.map(n=><a key={n} onClick={()=>setMenu(false)} href={'#'+n.toLowerCase().replace(' ','-')}>{n}</a>)}</nav><div className="head-actions"><button className="icon" onClick={theme} aria-label="Change color theme">{light?<Moon size={18}/>:<Sun size={18}/>}</button><a className="button compact" href="#contact">Request a Quote <ArrowUpRight size={15}/></a><button className="icon mobile" onClick={()=>setMenu(!menu)} aria-label="Open menu">{menu?<X/>:<Menu/>}</button></div></header>
    <section className="hero" id="home"><div className="hero-grid" /><div className="hero-content"><div className="eyebrow"><span /> DIGITAL DETAILING / GLOBAL COLLABORATION</div><h1>Precision in Every Detail.<br/><em>Confidence</em> in Every Structure.</h1><p>MV Designers delivers accurate, fabrication-ready structural steel detailing solutions for fabricators, engineers, and construction professionals.</p><div className="hero-ctas"><a className="button" href="#services">Explore Capabilities <ArrowUpRight size={17}/></a><a className="text-link" href="#contact">Request a Quote <ChevronRight size={16}/></a></div><p className="trust"><Check size={14}/> Precision-led detailing for complex structural steel requirements.</p></div><SteelModel/><div className="tech-list"><span><i />3D MODELING</span><span><i />SHOP DRAWINGS</span><span><i />ERECTION DRAWINGS</span><span><i />CNC / DSTV</span></div><a className="scroll" href="#about">VIEW OUR PROCESS <ArrowDown size={16}/></a></section>
    <div className="marquee"><div>STRUCTURAL STEEL DETAILING <b>◆</b> 3D MODELING <b>◆</b> SHOP DRAWINGS <b>◆</b> ERECTION DRAWINGS <b>◆</b> CNC / DSTV <b>◆</b> PRECISION <b>◆</b> QUALITY <b>◆</b> INNOVATION <b>◆</b></div></div>
    <section className="about section" id="about"><aside>01 / ABOUT MV DESIGNERS</aside><div><p className="eyebrow">ENGINEERING, DELIVERED WITH PURPOSE</p><h2>Clarity at every<br/><em>connection.</em></h2></div><div className="bodycopy"><p>{company.description} We focus on the accuracy and innovation needed to turn complex design information into concise, easy-to-read deliverables.</p><div className="values">{company.values.map(x=><span key={x}>{x}</span>)}</div><a className="text-link" href="#services">Discover our approach <ArrowUpRight size={16}/></a></div></section>
    <section className="statement"><div className="micro-grid"/><p>Every connection matters. Every dimension carries responsibility. Every detail contributes to the final structure.</p></section>
    <section className="services section" id="services"><aside>02 / SERVICES</aside><div className="services-copy"><p className="eyebrow">TECHNICAL CAPABILITIES</p><h2>Detailing that moves<br/><em>the work forward.</em></h2><p>Each output is designed to support a clear, coordinated path from model to fabrication.</p></div><div className="service-panel"><div className="service-nav">{services.map(([title],i)=><button className={active===i?'selected':''} onClick={()=>setActive(i)} key={title}><b>{String(i+1).padStart(2,'0')}</b>{title}<ChevronRight size={16}/></button>)}</div><article><span className="service-no">{String(active+1).padStart(2,'0')}</span><h3>{services[active][0]}</h3><p>{services[active][1]}</p><div className="output"><span>MODEL-BASED</span><span>PROJECT OUTPUT</span><span>TECHNICAL REVIEW</span></div><a className="button" href="#contact">Discuss this service <ArrowUpRight size={16}/></a></article></div></section>
    <section className="process" id="process"><div className="section-heading"><p className="eyebrow">03 / ENGINEERING WORKFLOW</p><h2>From contract drawing<br/>to <em>fabrication.</em></h2></div><div className="pipeline">{workflow.map((item,i)=><div key={item}><b>{String(i+1).padStart(2,'0')}</b><span>{item}</span>{i < workflow.length-1 && <i />}</div>)}</div></section>
    <section className="twin section" id="capabilities"><aside>04 / CAPABILITIES</aside><div><p className="eyebrow">DIGITAL TWIN THINKING</p><h2>From drawing to<br/><em>digital twin.</em></h2><p>Structured information becomes a coordinated model, then a fabrication-ready set of outputs.</p></div><div className="blueprint"><span>CONTRACT DRAWING</span><div className="drawing"><i/><i/><i/><i/><i/></div><span>MODEL COORDINATION / 01</span></div></section>
    <section className="why" id="why-mv"><div className="section-heading"><p className="eyebrow">05 / WHY MV DESIGNERS</p><h2>Built on discipline.<br/><em>Driven by detail.</em></h2></div><div className="feature-grid">{[['01','Precision','Accurate and clear detailing.'],['02','Quality','A focused approach to deliverables.'],['03','Efficiency','Streamlined technical workflows.'],['04','Innovation','Modern detailing techniques.'],['05','Reliability','Consistent project-focused service.'],['06','Integrity','Professional, transparent relationships.']].map(x=><article key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p><span>+</span></article>)}</div></section>
    <section className="quality"><div className="crosshair">⊹</div><p className="eyebrow">QUALITY CONTROL / VERIFIED CLARITY</p><h2>Getting it right<br/><em>the first time.</em></h2><div><span>ACCURACY</span><span>CLARITY</span><span>CONSISTENCY</span><span>FABRICATION-READY</span></div></section>
    <section className="showcase" id="gallery"><div className="showcase-image" role="img" aria-label="Structural steel frame at night"><div className="image-caption">MODEL / DETAIL / FABRICATE</div></div><div className="showcase-copy"><p className="eyebrow">06 / COORDINATED OUTPUT</p><h2>Steel, seen through<br/><em>a more precise lens.</em></h2><p>From contract information to final outputs, the work is organized around clarity. No unnecessary complexity—just the right technical information at the right stage.</p><div className="showcase-points"><span><Check/> Model coordination</span><span><Check/> Drawing clarity</span><span><Check/> Fabrication output</span></div></div></section>
    <section className="global"><div><p className="eyebrow">GLOBAL COLLABORATION</p><h2>Seamless support.<br/><em>One connected team.</em></h2><p>Supporting global structural steel detailing requirements through coordinated India-based engineering capabilities.</p></div><div className="world"><span className="us">US<br/><b>Eastern Time</b><strong>{clocks.us}</strong></span><i/><span className="india">INDIA<br/><b>India Standard Time</b><strong>{clocks.india}</strong></span><small>● GLOBAL SUPPORT AVAILABLE</small></div></section>
    <section className="contact contact-direct" id="contact"><aside>07 / CONTACT</aside><div><p className="eyebrow">START A CONVERSATION</p><h2>Let’s detail your<br/><em>next project.</em></h2><p>Have a structural steel project in development? Connect directly with the MV Designers team to discuss your detailing requirements.</p></div><div className="connect-panel"><Mail size={27}/><span>PROJECT ENQUIRIES</span><a href={`mailto:${company.contact.email}?subject=MV%20Designers%20Project%20Enquiry`}>{company.contact.email}</a><p>Opens your default email app—Gmail, Outlook, Apple Mail, or another configured mail client.</p><a className="button" href={`mailto:${company.contact.email}?subject=MV%20Designers%20Project%20Enquiry`}>Connect with us <Send size={16}/></a><small><ShieldCheck size={13}/> Private project details should be shared only through a confirmed company email.</small></div></section>
    <section className="final"><p className="eyebrow">MV DESIGNERS / STRUCTURAL DETAILING</p><h2>Precision starts with the right<br/><em>detailing partner.</em></h2><a className="button" href="#contact">Request a Quote <ArrowUpRight size={17}/></a></section>
    <footer><a className="brand" href="#home"><small>STRUCTURAL</small>MV DESIGNERS</a><p>{company.tagline}</p><div><a href="#about">About</a><a href="#services">Services</a><a href="#contact">Contact</a></div><small>STRUCTURAL DETAILING • DIGITAL PRECISION • GLOBAL COLLABORATION<br/>© {new Date().getFullYear()} MV Designers. Editable company contact details should be added before launch.</small></footer>
    <div className="chat-wrap"><button className="chat" onClick={()=>setChat(!chat)} aria-label="Open MV Assistant" aria-expanded={chat}><MessageCircle /></button>{chat&&<section className="chatbox" aria-label="MV Assistant"><b>MV ASSISTANT</b>{chatQuestion && <p className="chat-user">You: {chatQuestion}</p>}<p aria-live="polite">{chatReply}</p><div className="chat-options"><button onClick={()=>answer('services')}>Our Services</button><button onClick={()=>answer('quote')}>Request a Quote</button><button onClick={()=>answer('hours')}>Working Hours</button></div><form onSubmit={submitChat}><label className="sr-only" htmlFor="chat-message">Ask MV Assistant</label><input id="chat-message" value={chatInput} onChange={event=>setChatInput(event.target.value)} placeholder="Ask a question…" disabled={chatSending}/><button type="submit" aria-label="Send message" disabled={chatSending}><Send size={15}/></button></form></section>}</div><a className="top" href="#home" aria-label="Back to top"><ArrowDown /></a>
  </main>;
}
